# Generated by Django 6.0.5 on 2026-08-31 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbproduct',
            options={'ordering': ['product_name'], 'verbose_name': 'BB Product', 'verbose_name_plural': 'BB Products'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='branchinventory',
            options={'verbose_name': 'Branch Inventory', 'verbose_name_plural': 'Branch Inventories'},
        ),
        migrations.AlterModelOptions(
            name='pangananmenu',
            options={'ordering': ['category', 'menu'], 'verbose_name': 'Panganan Menu', 'verbose_name_plural': 'Panganan Menus'},
        ),
        migrations.AlterModelOptions(
            name='vrealproduct',
            options={'ordering': ['category', 'product'], 'verbose_name': 'VReal Product', 'verbose_name_plural': 'VReal Products'},
        ),
        migrations.AlterModelOptions(
            name='vssservice',
            options={'ordering': ['category', 'description'], 'verbose_name': 'VSS Service', 'verbose_name_plural': 'VSS Services'},
        ),
        migrations.AddField(
            model_name='autospaservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bbproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bbproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='branchinventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kbitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pangananmenu',
            name='category',
            field=models.CharField(choices=[('BURGER', 'Burgers'), ('SILOG', 'Silog Meals'), ('SIZZLING', 'Sizzling'), ('WINGS', 'Chicken Wings'), ('BOWL', 'Rice Bowls'), ('VEGETABLE', 'Vegetable'), ('MERIENDA', 'Merienda'), ('BEVERAGE', 'Beverages'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
        migrations.AddField(
            model_name='pangananmenu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtable',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomtable',
            name='room_type',
            field=models.CharField(choices=[('PEDICURE', 'Pedicure & Manicure'), ('FOOT_SPA', 'Foot Spa'), ('MASSAGE', 'Massage Room'), ('VIP', 'VIP Room')], default='PEDICURE', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtable',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomtable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vrealproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vrealproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vssservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branchinventory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='branchinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventories', to='api.product'),
        ),
        migrations.AlterField(
            model_name='roomtable',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomtable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='vrealproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('SOAP', 'Soap'), ('FS_WASH', 'F/S Wash'), ('TONER', 'Toner'), ('NIGHT_CREAM', 'Night Cream'), ('MOISTURIZER', 'Moisturizer'), ('SUNBLOCK', 'Sunblock'), ('SERUM', 'Serum'), ('SET', 'Set'), ('GLUTA', 'Glutathione'), ('HAIR_CARE', 'Hair Care'), ('LOTION', 'Lotion'), ('OTHERS', 'Others'), ('SALON_PRODUCTS', 'Salon Products')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vssservice',
            name='category',
            field=models.CharField(blank=True, choices=[('RADIO_FREQUENCY', 'Radio Frequency'), ('SALON_SERVICES', 'Salon Services'), ('HAND_FOOT_TREATMENT', 'Hand and Foot Treatment'), ('FACIAL_TREATMENT', 'Facial Treatment'), ('LASER_TREATMENT', 'Laser Treatment'), ('BLEACHING_WHITENING', 'Instant Bleaching and Skin Whitening'), ('HIFU_ULTERA', 'HIFU - Ultera'), ('PICO_WAY', 'Pico Way'), ('EYELASH_EXTENSIONS', 'Eyelash Extensions'), ('GLYCOLIC_PEELING', 'Glycolic Peeling'), ('SKIN_GROWTH_REMOVAL', 'Skin Growth Removal'), ('WAXING', 'Waxing'), ('MASSAGE', 'Massage'), ('MICRODERMABRASION', 'Microdermabrasion'), ('BODY_SCRUB', 'Body Scrub'), ('AESTHETIC_TATTOO', 'Aesthetic Tattoo/Semi Permanent Tattoo'), ('PROMO_PRICE', 'Promo Price'), ('PERMANENT_HAIR_REMOVAL', 'Permanent Hair Removal'), ('OTHER_SERVICES', 'Other Services')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('VOID', 'Void'), ('RETURN', 'Return'), ('HOLD', 'Hold')], default='SALE', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clientprofile')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vssservice')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_void', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
