# Generated by Django 4.2.16 on 2026-09-24 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_expense_customerfeedback_auditlog_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('VSS', 'VSS Services Branch'), ('VREAL', 'VReal Products Branch'), ('BB', 'BB Products Branch'), ('MIXED', 'Mixed (VSS + VReal + BB)')], default='VSS', help_text='Determines which catalog this branch offers in POS', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='catalog_source',
            field=models.CharField(choices=[('VSS', 'VSS Service'), ('VREAL', 'VReal Product'), ('BB', 'BB Product'), ('GENERIC', 'Generic Product')], default='GENERIC', help_text='Which catalog the item came from (VSS/VREAL/BB)', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='api.clientprofile'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
