# Generated by Django 4.2.16 on 2026-09-24 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_attendance_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FREE_ITEM', 'Free Item'), ('POINTS', 'Points'), ('TIER_UPGRADE', 'Tier Upgrade')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount or points value', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (if applicable)', max_digits=5)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Reward',
                'verbose_name_plural': 'Customer Rewards',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='free_items_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='loyalty_tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_tier_at_purchase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tier_discount_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_claims_made', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.customerreward')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_claims', to='api.transaction')),
            ],
            options={
                'verbose_name': 'Reward Claim',
                'verbose_name_plural': 'Reward Claims',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddField(
            model_name='customerreward',
            name='claimed_in_transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction where this reward was claimed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_claimed', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.clientprofile'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction where this reward was earned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_generated', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rewards_applied',
            field=models.ManyToManyField(blank=True, help_text='Rewards claimed in this transaction', related_name='applied_in_transactions', to='api.customerreward'),
        ),
    ]
