# Generated by Django 5.1.8 on 2026-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_customerreward_clientprofile_age_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autospaservice",
            options={
                "ordering": ["service"],
                "verbose_name": "Auto Spa Service",
                "verbose_name_plural": "Auto Spa Services",
            },
        ),
        migrations.AlterModelOptions(
            name="branch",
            options={
                "ordering": ["name"],
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.AlterModelOptions(
            name="branchinventory",
            options={
                "ordering": ["branch__name", "product__name"],
                "verbose_name": "Branch Inventory",
                "verbose_name_plural": "Branch Inventories",
            },
        ),
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="dailysales",
            options={
                "ordering": ["-date"],
                "verbose_name": "Daily Sales",
                "verbose_name_plural": "Daily Sales",
            },
        ),
        migrations.AlterModelOptions(
            name="kbitem",
            options={
                "ordering": ["name"],
                "verbose_name": "KB Item",
                "verbose_name_plural": "KB Items",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtable",
            options={
                "ordering": ["branch__name", "name"],
                "verbose_name": "Room Table",
                "verbose_name_plural": "Room Tables",
            },
        ),
        migrations.AlterModelOptions(
            name="transactionitem",
            options={
                "ordering": ["transaction_id", "id"],
                "verbose_name": "Transaction Item",
                "verbose_name_plural": "Transaction Items",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["user__username"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("VOIDED", "Voided"),
                    ("HELD", "Held"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
