# Generated by Django 5.1.8 on 2026-09-28 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_autospaservice_options_alter_branch_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="business/"),
                ),
                ("receipt_header", models.TextField(blank=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("loyalty_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Businesses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("default_unit", models.CharField(default="pc", max_length=20)),
                ("tracks_stock", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("PRODUCT", "Product"), ("SERVICE", "Service")],
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        default="Bungad & Villareal Group", max_length=200
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("tax_id", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("default_currency", models.CharField(default="PHP", max_length=3)),
                ("timezone", models.CharField(default="Asia/Manila", max_length=64)),
                (
                    "default_tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("receipt_footer", models.TextField(blank=True)),
                ("loyalty_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company",
            },
        ),
        migrations.CreateModel(
            name="InventoryLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_qty", models.IntegerField(default=0)),
                ("reorder_point", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("PRODUCT", "Product"), ("SERVICE", "Service")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=64)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("tracks_stock", models.BooleanField(default=True)),
                ("min_stock", models.PositiveIntegerField(default=0)),
                ("unit", models.CharField(default="pc", max_length=20)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_unit",
                    models.CharField(
                        blank=True,
                        choices=[("MIN", "Minutes"), ("HOUR", "Hours")],
                        max_length=5,
                    ),
                ),
                ("requires_staff", models.BooleanField(default=False)),
                ("requires_room", models.BooleanField(default=False)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("VOID", "Void/Return"),
                            ("RECEIVE", "Stock received"),
                            ("ADJUST", "Manual adjustment"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("WASTE", "Damage/Waste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("balance_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("COMPANY_ADMIN", "Company Admin"),
                            ("ACCOUNTANT", "Accountant"),
                            ("BUSINESS_MANAGER", "Business Manager"),
                            ("SUPERVISOR", "Supervisor"),
                            ("CASHIER", "Cashier"),
                            ("STAFF", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Business the user lands on after login",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["user__username", "business__name"],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("user", "branch", "date")},
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["phone_number"], name="api_clientp_phone_n_eb8799_idx"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="customerfeedback",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="dailysales",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_sales",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="roomtable",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="businessitem",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_entries",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="business_type",
            field=models.ForeignKey(
                help_text="Spa / Restaurant / Auto shop ... determines default item kinds",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="businesses",
                to="api.businesstype",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="inventorylevel",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_levels",
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="inventorylevel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_levels",
                to="api.item",
            ),
        ),
        migrations.AddField(
            model_name="businessitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_entries",
                to="api.item",
            ),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction_items",
                to="api.item",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Services this staff member can perform",
                related_name="skilled_staff",
                to="api.item",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="api.item",
            ),
        ),
        migrations.AddField(
            model_name="useraccess",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Empty = all branches of the business",
                related_name="access_grants",
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="useraccess",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL = company-wide role",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_grants",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="useraccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "kind")},
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_type", "is_active"], name="api_item_item_ty_c17c9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["barcode"], name="api_item_barcode_301681_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("name", "item_type")},
        ),
        migrations.AddConstraint(
            model_name="inventorylevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_qty__gte", 0)), name="inventory_non_negative"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorylevel",
            unique_together={("branch", "item")},
        ),
        migrations.AlterUniqueTogether(
            name="businessitem",
            unique_together={("business", "item")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["item", "created_at"], name="api_stockmo_item_id_09cd0a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", True),
                        ("role__in", ["OWNER", "COMPANY_ADMIN", "ACCOUNTANT"]),
                    ),
                    models.Q(
                        ("role__in", ["OWNER", "COMPANY_ADMIN", "ACCOUNTANT"]),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="company_role_has_no_business",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useraccess",
            unique_together={("user", "role", "business")},
        ),
    ]
