# Generated by Django 5.1.8 on 2026-09-28 10:40

from django.db import migrations, models


def backfill_unified_sales_links(apps, schema_editor):
    """Copies legacy catalog links into the unified catalog.

    Runs first in 0010, while the retired tables still exist, so that:
    1. ``TransactionItem.item`` is set from the legacy ``product``/``service``
       FKs (preserves sales history after those columns are dropped);
    2. ``UserProfile.services`` (VSSService ids) is copied into ``skills``
       (unified Item ids) before the old M2M table is dropped;
    3. ``Category`` rows created by 0009 from raw category codes are renamed
       to their display labels (``RADIO_FREQUENCY`` -> ``Radio Frequency``),
       mirroring the old ``get_category_display`` values.
    """
    Item = apps.get_model('api', 'Item')
    Category = apps.get_model('api', 'Category')
    TransactionItem = apps.get_model('api', 'TransactionItem')
    UserProfile = apps.get_model('api', 'UserProfile')
    VSSService = apps.get_model('api', 'VSSService')

    # 1. Transaction line history -> Item
    for line in TransactionItem.objects.filter(item__isnull=True).select_related(
        'product', 'service'
    ):
        match = None
        if line.product_id:
            match = Item.objects.filter(
                name=line.product.name.strip(), item_type='PRODUCT'
            ).first()
        elif line.service_id:
            match = Item.objects.filter(
                name=line.service.description.strip(), item_type='SERVICE'
            ).first()
        if match is not None:
            line.item = match
            line.save(update_fields=['item'])

    # 2. Staff skills -> Items
    try:
        legacy_through = UserProfile.services.through
    except AttributeError:
        legacy_through = None
    if legacy_through is not None:
        skill_through = UserProfile.skills.through
        existing = set(skill_through.objects.values_list('userprofile_id', 'item_id'))
        for row in legacy_through.objects.all():
            legacy = VSSService.objects.filter(pk=row.vssservice_id).first()
            if legacy is None:
                continue
            item = Item.objects.filter(
                name=legacy.description.strip(), item_type='SERVICE'
            ).first()
            if item is None:
                continue
            if (row.userprofile_id, item.id) not in existing:
                skill_through.objects.create(
                    userprofile_id=row.userprofile_id, item_id=item.id
                )
                existing.add((row.userprofile_id, item.id))

    # 3. Category codes -> display labels (collision-safe)
    for model_name, kind in (
        ('VSSService', 'SERVICE'),
        ('VRealProduct', 'PRODUCT'),
        ('PangananMenu', 'PRODUCT'),
        ('Product', 'PRODUCT'),
    ):
        model = apps.get_model('api', model_name)
        choices = dict(model._meta.get_field('category').choices)
        for code, label in choices.items():
            if not code or label == code:
                continue
            for cat in Category.objects.filter(name=code, kind=kind):
                if not Category.objects.filter(name=label, kind=kind).exclude(
                    pk=cat.pk
                ).exists():
                    cat.name = label
                    cat.save(update_fields=['name'])


def noop_reverse(apps, schema_editor):
    # Forward-only: legacy tables are recreated empty on a backwards migrate.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_unified_catalog"),
    ]

    operations = [
        migrations.RunPython(backfill_unified_sales_links, noop_reverse),
        migrations.DeleteModel(
            name="AutoSpaService",
        ),
        migrations.DeleteModel(
            name="BBProduct",
        ),
        migrations.AlterUniqueTogether(
            name="branchinventory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="branchinventory",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="branchinventory",
            name="product",
        ),
        migrations.DeleteModel(
            name="KBItem",
        ),
        migrations.DeleteModel(
            name="PangananMenu",
        ),
        migrations.RemoveField(
            model_name="transactionitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="VRealProduct",
        ),
        migrations.RemoveField(
            model_name="transactionitem",
            name="service",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="services",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Services this staff member can perform (unified catalog Items)",
                related_name="skilled_staff",
                to="api.item",
            ),
        ),
        migrations.DeleteModel(
            name="BranchInventory",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="VSSService",
        ),
    ]
