# Generated by Django 5.1.8 on 2026-09-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_transaction_item_branch_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionitem",
            name="catalog_source",
            field=models.CharField(
                choices=[
                    ("VSS", "VSS Service"),
                    ("VREAL", "VReal Product"),
                    ("BB", "BB Product"),
                    ("GENERIC", "Generic Product"),
                ],
                default="GENERIC",
                help_text="Which legacy catalog the item came from (VSS/VREAL/BB) — derived, kept for receipts",
                max_length=20,
            ),
        ),
    ]
