# Generated by Django 5.1.8 on 2026-09-30 06:55

from django.conf import settings
from django.db import migrations, models


def split_platform_operators(apps, schema_editor):
    """Re-label the accounts that were SUPERADMIN back when it meant OWNER.

    §6.3 folded SUPERADMIN into OWNER, so every platform operator's grant was
    rewritten to role='OWNER'.  With the two roles distinct again, those rows
    have to become SUPERADMIN or the operator would silently resolve to OWNER —
    which is denied the very platform actions they exist to perform.  An
    account qualifies if it is a Django superuser or sits in a legacy
    "Superadmin" group; where a SUPERADMIN grant already exists the stale OWNER
    one is dropped (the unique key is (user, role, business), so leaving both
    would give the account two competing grants).
    """
    UserAccess = apps.get_model("api", "UserAccess")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    for user in User.objects.all():
        is_platform = user.is_superuser or user.groups.filter(
            name__in=["SUPERADMIN", "Superadmin"]
        ).exists()
        if not is_platform:
            continue
        for grant in UserAccess.objects.filter(user=user, role="OWNER"):
            if UserAccess.objects.filter(
                user=user, role="SUPERADMIN", business_id=grant.business_id
            ).exists():
                grant.delete()
            else:
                grant.role = "SUPERADMIN"
                grant.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_devicetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="useraccess",
            name="company_role_has_no_business",
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Superadmin"),
                    ("OWNER", "Owner"),
                    ("COMPANY_ADMIN", "Company Admin"),
                    ("ACCOUNTANT", "Accountant"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("SUPERVISOR", "Supervisor"),
                    ("CASHIER", "Cashier"),
                    ("STAFF", "Staff"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", True),
                        (
                            "role__in",
                            ["SUPERADMIN", "OWNER", "COMPANY_ADMIN", "ACCOUNTANT"],
                        ),
                    ),
                    models.Q(
                        (
                            "role__in",
                            ["SUPERADMIN", "OWNER", "COMPANY_ADMIN", "ACCOUNTANT"],
                        ),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="company_role_has_no_business",
            ),
        ),
        migrations.RunPython(split_platform_operators, migrations.RunPython.noop),
    ]
