# Generated by Django 5.1.8 on 2026-09-30 09:27

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_clients(apps, schema_editor):
    """Give every pre-existing customer an owning business.

    ``ClientProfile`` had no ``business`` column, so the customers table was
    shared by every tenant. Now that it does, an owner has to be chosen or the
    customer is invisible to every business-scoped user (and to the cashier who
    needs them at the till).

    Best evidence first: the business of a transaction the customer actually
    paid at. Failing that, the first business on the platform — a judgement
    call, but leaving the row NULL would silently hide real customers.
    """
    ClientProfile = apps.get_model('api', 'ClientProfile')
    Transaction = apps.get_model('api', 'Transaction')

    default_business = None
    for client in ClientProfile.objects.filter(business__isnull=True).iterator():
        business_id = (
            Transaction.objects
            .filter(customer=client)
            .exclude(business_id=None)
            .values_list('business_id', flat=True)
            .first()
        )
        if business_id is None:
            if default_business is None:
                default_business = (
                    apps.get_model('api', 'Business').objects
                    .order_by('id').values_list('id', flat=True).first()
                )
            business_id = default_business
        if business_id is not None:
            ClientProfile.objects.filter(pk=client.pk).update(business_id=business_id)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_split_superadmin_from_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="api.business",
            ),
        ),
        migrations.RunPython(assign_existing_clients, migrations.RunPython.noop),
    ]
