# Generated by Django 5.1.8 on 2026-09-30 16:36

import api.access.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_clientprofile_business"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashierShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "opening_float",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closing_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "expected_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "over_short",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-opened_at"],
            },
            bases=(api.access.managers.BusinessStampMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(default="TXN", max_length=10)),
                ("period", models.CharField(max_length=12)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Document sequences",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earn_amount",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "redeem_value",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "free_item_threshold",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "points_valid_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Loyalty programs",
            },
            bases=(api.access.managers.BusinessStampMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("EARN", "Earned on sale"),
                            ("REDEEM", "Redeemed"),
                            ("ADJUST", "Manual adjustment / void reversal"),
                            ("EXPIRE", "Expired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tendered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
            bases=(api.access.managers.BusinessStampMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(api.access.managers.BusinessStampMixin, models.Model),
        ),
        migrations.AddField(
            model_name="business",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_businesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("business__isnull", True), ("is_active", True), ("role", "OWNER")
                ),
                fields=("role",),
                name="single_active_owner",
            ),
        ),
        migrations.AddField(
            model_name="cashiershift",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashier_shifts",
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="cashiershift",
            name="business",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="cashiershift",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashier_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="api.cashiershift",
            ),
        ),
        migrations.AddField(
            model_name="documentsequence",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_sequences",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="loyaltyprogram",
            name="business",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytransaction",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loyalty_entries",
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytransaction",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_transactions",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loyalty_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loyaltytransaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_entries",
                to="api.clientprofile",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytransaction",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loyalty_entries",
                to="api.transaction",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="business",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="api.cashiershift",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="api.transaction",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="business",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="api.paymentmethod",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashiershift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("branch", "staff"),
                name="one_open_shift_per_staff_per_branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentsequence",
            unique_together={("business", "prefix", "period")},
        ),
        migrations.AlterUniqueTogether(
            name="loyaltyprogram",
            unique_together={("business",)},
        ),
        migrations.AddIndex(
            model_name="loyaltytransaction",
            index=models.Index(
                fields=["customer", "created_at"], name="api_loyalty_custome_3b715e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltytransaction",
            index=models.Index(
                fields=["business", "created_at"], name="api_loyalty_busines_101459_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("points__gt", 0), ("points__lt", 0), _connector="OR"
                ),
                name="loyalty_entry_nonzero",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("business", "code")},
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
    ]
